name: Maintain Ardoq Tech Stack
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
  push:
    branches:
      - master
      - main
      - fix-github-action
jobs:
  Maintain-Ardoq-Tech-Stack:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - name: List dependencies
        run: |
          cat yarn.lock | base64 > yarn.lock.b64
        id: deps

      - name: Prepare request payload
        run: |
          echo -n '{
            "vcsHost": "github.com/hmcts",
            "hmctsApplication": "dtsse",
            "codeRepository": "dtsse-ardoq-adapter",
            "encodedDependecyList": "' > payload.json
          cat yarn.lock.b64 | tr -d '\n' >> payload.json
          echo -n '",
              "parser": "yarn"
            }' >> payload.json

      - name: compress body
        run: |
          gzip payload.json

      - name: debug compression
        run: |
          ls -lah payload.json.gz

      - name: post deps to ardoq app
        run: |
          curl --location --request POST '${{ secrets.ARDOQ_ADAPTER_URL }}' \
            --header 'Authorization: Bearer ${{ secrets.ARDOQ_ADAPTER_KEY }}' \
            --header 'Content-Type: application/json' \
            --header 'content-encoding: gzip' \
            --data-binary '@payload.json.gz'

      - run: echo "üçè This job's status is ${{ job.status }}."
